version: "3.9"
services:
  nodedoc:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    links:
      - mysqldoc
    volumes:
      - .:/home/app
  mysqldoc:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1qaz7ujmP$
      - MYSQL_DATABASE=animecream
      - MYSQL_USER=ander
      - MYSQL_PASSWORD=GAnimeP$7
    volumes:
      - mysql-data:/var/lib/mysql
      # mongo-data:/data/db
      # postgres -> /var/lib/postgresql/data

volumes:
  mysql-data:
